name: Run CircleCI artifacts redirector, rendered pages are under Details

on: [status]
jobs:
  circleci_artifacts_redirector_job:
    runs-on: ubuntu-latest
    name: Run CircleCI artifacts redirector
    steps:
      - name: GitHub Action step
        uses: larsoner/circleci-artifacts-redirector-action@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          api-token: ${{ secrets.ASTROML_NOTEBOOKS_CIRCLE_TOKEN }}
          artifact-path: 0/_build/html/index.html
          circleci-jobs: build-docs